[package]
name = "app-lib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13.20"
serde = { version = "1.0.127", features = ["derive"] }
thiserror = "1.0.26"
tokio = "1.9.0"
